OUTPUT_DIR:
  './log_CUSTOM_DATASET_FINAL'

DATASET:
  name: 'CUSTOM_MASK_ND'
  custom_object_name: 'dataset_final'

  # Split according to /nas_homes/dataset/dataset_final/split_samples.py naming convention:
  #   ..._train_... -> train split
  #   ..._test_...  -> test split
  custom_split_by_filename_tag: True
  custom_split_train_tag: '_train_'
  custom_split_test_tag: '_test_'

  # During evaluation, sample support images from the train split only (no test-image leakage into support).
  custom_support_from_train: True

  image_size: 518
  mask_size: 518
  unified_mask_size: 4500
  rotate_min: -10
  rotate_max: 10

  area_resize_ratio: 0.01
  crop_size: 518
  crop_ratio: [ 1.0, 1.0 ]

  test_sample_repeated_multiple: 1
  few_shot_repeated_multiple: 1
  shot: 1
  s_in_shot: 4
  split: 0

  normal_sample_sampling_prob: 0.3

TRAIN:
  enable: True
  save_model: True
  method: 'SOFS'

  # New dataset paths
  dataset_path: '/nas_homes/dataset/dataset_final/data/images'
  mask_path: '/nas_homes/dataset/dataset_final/data/masks'

  backbone: 'dinov2_vitb14'
  backbone_load_state_dict: True
  backbone_checkpoint: './dinov2_vitb14_pretrain.pth'

  load_checkpoint: False
  load_model_path: "./"

  SOFS:
    prior_layer_pointer: [5, 6, 7, 8, 9, 10]
    target_semantic_temperature: 0.1
    reduce_dim: 256
    transformer_embed_dim: 256

    transformer_num_stages: 2
    transformer_nums_heads: 4

    meta_cls: True
    normal_sim_aug: True

    # Training behavior for dataset_final:
    # - Exclude normal images from episodic defect-localization training (query/support episodes).
    # - Use normal images only for the "mixed normal dice" regularizer (see utils.common.dice_binary_loss f_normal).
    exclude_normal_from_episode: True
    mndl_weight: 1.0

    conv_vit_down_sampling: True
    vit_patch_size: 14

    smooth_r: 1e5

  LOSS:
    dice_weight: 1.
    ce_weight: 0.01

TRAIN_SETUPS:
  batch_size: 2
  num_workers: 4
  learning_rate: 1e-5
  optimizer_momentum: 0.9
  epochs: 50
  weight_decay: 0.01

  poly_training: True
  lr_multiple: 2.

  TEST_SETUPS:
    test_state: True
    epoch_test: 50
    train_miou: 50
    val_state: False

TEST:
  enable: False
  method: 'SOFS'

  dataset_path: '/nas_homes/dataset/dataset_final/data/images'
  mask_path: '/nas_homes/dataset/dataset_final/data/masks'

  load_checkpoint: False
  load_model_path: "./"

  VISUALIZE:
    save_figure: True
    sample_prob: 1.

TEST_SETUPS:
  batch_size: 1
  ND_batch_size: 1


